//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProgrami.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ameliyat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ameliyat()
        {
            this.ameliyatSonuc = new HashSet<ameliyatSonuc>();
        }
    
        public int ameliyatID { get; set; }
        public Nullable<int> bolumID { get; set; }
        public Nullable<int> hastaID { get; set; }
        public Nullable<int> hastaBilgiID { get; set; }
        public Nullable<int> tahlilID { get; set; }
        public Nullable<int> ameliyatOdasiID { get; set; }
        public Nullable<int> ameliyatEkibiID { get; set; }
        public Nullable<bool> onay { get; set; }
        public string belge { get; set; }
        public string ad { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> ameliyatBaslangicTarih { get; set; }
        public Nullable<System.TimeSpan> ameliyatBaslangicSaati { get; set; }
        public System.DateTime onayTarih { get; set; }
    
        public virtual hastaBilgi hastaBilgi { get; set; }
        public virtual tahlil tahlil { get; set; }
        public virtual ameliyatOdasi ameliyatOdasi { get; set; }
        public virtual ameliyatEkip ameliyatEkip { get; set; }
        public virtual bolum bolum { get; set; }
        public virtual hasta hasta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ameliyatSonuc> ameliyatSonuc { get; set; }
    }
}
