//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProgrami.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class hasta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hasta()
        {
            this.ameliyat = new HashSet<ameliyat>();
            this.hastaBilgi = new HashSet<hastaBilgi>();
            this.muayene = new HashSet<muayene>();
            this.randevu = new HashSet<randevu>();
            this.recete = new HashSet<recete>();
            this.tahlil = new HashSet<tahlil>();
        }
    
        public int hastaID { get; set; }
        public Nullable<int> vatandasYetkiID { get; set; }
        public Nullable<int> kanGrubuID { get; set; }
        public string TCKimlikNo { get; set; }
        public string sifre { get; set; }
        public string rsifre { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public System.DateTime dogumTarihi { get; set; }
        public string adres { get; set; }
        public string email { get; set; }
        public bool cinsiyet { get; set; }
        public Nullable<bool> medeniHali { get; set; }
        public string meslek { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public string cepTel { get; set; }
        public string evTel { get; set; }
        public string isTel { get; set; }
        public string dogumYeri { get; set; }
        public string sicilNo { get; set; }
        public string sgk { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string anne { get; set; }
        public string baba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ameliyat> ameliyat { get; set; }
        public virtual kanGrubu kanGrubu { get; set; }
        public virtual vatandasYetki vatandasYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hastaBilgi> hastaBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<muayene> muayene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<randevu> randevu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recete> recete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tahlil> tahlil { get; set; }
    }
}
