//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProgrami.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class hastaBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hastaBilgi()
        {
            this.ameliyat1 = new HashSet<ameliyat>();
        }
    
        public int hastaBilgiID { get; set; }
        public int hastaID { get; set; }
        public string alerjiler { get; set; }
        public string ilaclar { get; set; }
        public string hastalık { get; set; }
        public string ameliyat { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ameliyat> ameliyat1 { get; set; }
        public virtual hasta hasta { get; set; }
    }
}
