//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProgrami.Models.Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneContext : DbContext
    {
        public HastaneContext()
            : base("name=HastaneContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<hastaBilgi> hastaBilgi { get; set; }
        public virtual DbSet<hastaSikayet> hastaSikayet { get; set; }
        public virtual DbSet<idrarTup> idrarTup { get; set; }
        public virtual DbSet<kanGrubu> kanGrubu { get; set; }
        public virtual DbSet<kanTup> kanTup { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<muayene> muayene { get; set; }
        public virtual DbSet<muayeneSonuc> muayeneSonuc { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<poliklinik> poliklinik { get; set; }
        public virtual DbSet<randevu> randevu { get; set; }
        public virtual DbSet<randevuSaat> randevuSaat { get; set; }
        public virtual DbSet<recete> recete { get; set; }
        public virtual DbSet<receteBilgi> receteBilgi { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tahlil> tahlil { get; set; }
        public virtual DbSet<unvan> unvan { get; set; }
        public virtual DbSet<yetki> yetki { get; set; }
        public virtual DbSet<ameliyat> ameliyat { get; set; }
        public virtual DbSet<ameliyatKadro> ameliyatKadro { get; set; }
        public virtual DbSet<ameliyatOdasi> ameliyatOdasi { get; set; }
        public virtual DbSet<ameliyatEkip> ameliyatEkip { get; set; }
        public virtual DbSet<bolum> bolum { get; set; }
        public virtual DbSet<hastaneOda> hastaneOda { get; set; }
        public virtual DbSet<vatandasYetki> vatandasYetki { get; set; }
        public virtual DbSet<hasta> hasta { get; set; }
        public virtual DbSet<ameliyatSonuc> ameliyatSonuc { get; set; }
    }
}
