//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProgrami.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kullaniciID { get; set; }
        public int personelID { get; set; }
        public int yetkiID { get; set; }
        public string adi { get; set; }
        public string sifre { get; set; }
    
        public virtual personel personel { get; set; }
        public virtual yetki yetki { get; set; }
    }
}
