//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProgrami.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class muayene
    {
        public int muayeneID { get; set; }
        public int hastaID { get; set; }
        public int personelID { get; set; }
        public int randevuID { get; set; }
        public Nullable<int> tahlilID { get; set; }
        public string baslik { get; set; }
        public string aciklama { get; set; }
        public System.DateTime tarih { get; set; }
    
        public virtual personel personel { get; set; }
        public virtual randevu randevu { get; set; }
        public virtual tahlil tahlil { get; set; }
        public virtual hasta hasta { get; set; }
    }
}
