//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProgrami.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class randevu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public randevu()
        {
            this.muayene = new HashSet<muayene>();
        }
    
        public int randevuID { get; set; }
        public int personelID { get; set; }
        public int hastaID { get; set; }
        public int poliklinikID { get; set; }
        public int randevuSaatID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<System.TimeSpan> saat { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public Nullable<bool> durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<muayene> muayene { get; set; }
        public virtual personel personel { get; set; }
        public virtual poliklinik poliklinik { get; set; }
        public virtual randevuSaat randevuSaat { get; set; }
        public virtual hasta hasta { get; set; }
    }
}
