//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProgrami.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class receteBilgi
    {
        public int receteBilgiID { get; set; }
        public int receteID { get; set; }
        public string barkodNo { get; set; }
        public string ad { get; set; }
        public string doz { get; set; }
        public string adet { get; set; }
        public string kullanımSekli { get; set; }
        public string fiyat { get; set; }
        public string toplam { get; set; }
    
        public virtual recete recete { get; set; }
    }
}
