//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneProgrami.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tahlil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tahlil()
        {
            this.muayene = new HashSet<muayene>();
            this.ameliyat = new HashSet<ameliyat>();
        }
    
        public int tahlilID { get; set; }
        public int personelID { get; set; }
        public int hastaID { get; set; }
        public Nullable<int> kanTupID { get; set; }
        public Nullable<int> idrarTupID { get; set; }
        public string sonuc { get; set; }
        public string durum { get; set; }
        public string miktar { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual idrarTup idrarTup { get; set; }
        public virtual kanTup kanTup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<muayene> muayene { get; set; }
        public virtual personel personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ameliyat> ameliyat { get; set; }
        public virtual hasta hasta { get; set; }
    }
}
